name: Build Constitution
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Install tectonic
        run: |
          sudo apt-get install -y tectonic
      - name: Build PDF
        run: |
          pandoc constitution.md -o pdf/constitution.pdf --pdf-engine=tectonic \
                -V mainfont="JetBrainsMono-Regular.ttf" \
                -V mainfontoptions:BoldFont="JetBrainsMono-Bold.ttf" \
                -V mainfontoptions:ItalicFont="JetBrainsMono-Italic.ttf" \
                -V mainfontoptions:BoldItalicFont="JetBrainsMono-BoldItalic.ttf" \
                -V mainfontoptions:Path="fonts/ttf/"
