name: Build Constitution
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:                # Job-level permissions configuration starts here
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install xelatex
        run: sudo apt install -y texlive-xetex
      - name: Create pdf folder
        run: mkdir -p pdf
      - uses: docker://pandoc/core:2.9
        with: 
          args: >- 
            constitution.md
            -V 'JetBrainsMono-Regular.ttf'
            -V 'mainfontoptions:BoldFont=JetBrainsMono-Bold.ttf'
            -V 'mainfontoptions:ItalicFont=JetBrainsMono-Italic.ttf'
            -V 'mainfontoptions:BoldItalicFont=JetBrainsMono-BoldItalic.ttf'
            -V 'mainfontoptions:Path=fonts/ttf/'
            --pdf-engine=xelatex
            -o pdf/constitution.pdf
      - name: Commit files
        run: |
          git add pdf/*
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
